intf_libs = # Interface dependencies.
impl_libs = # Implementation dependencies.

lib{crails-tests}: {hxx ixx txx cxx}{**} $impl_libs $intf_libs

hxx{export}@./: cxx.importable = false

cxx.poptions =+  "-I$out_root" "-I$src_root"

{hbmia obja}{*}: cxx.poptions += -DLIBCRAILS_STATIC_BUILD
{hbmis objs}{*}: cxx.poptions += -DLIBCRAILS_SHARED_BUILD

lib{crails-tests}:
{
  cxx.export.poptions = "-I$out_root" "-I$src_root"
  cxx.export.libs = $intf_libs
}

liba{crails-tests}: cxx.export.poptions += -DLIBCRAILS_STATIC
libs{crails-tests}: cxx.export.poptions += -DLIBCRAILS_SHARED

if $version.pre_release
  lib{crails-tests}: bin.lib.version = "-$version.project_id"
else
  lib{crails-tests}: bin.lib.version = "-$version.major.$version.minor"

{hxx ixx txx}{*}:
{
  install         = include/crails/tests
  install.subdirs = true
}
